In [ ]:
import pandas as  pd 
import numpy as np

df = pd.read_csv("../Desktop/working_with_ai/Decoding_Customer_Value/Dataset.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
# Analyse the data set
[print(df.describe())]
print(df.info())

       Customer ID          Age  Purchase Amount (USD)  Review Rating  \
count  3900.000000  3900.000000            3900.000000    3863.000000
mean   1950.500000    44.068462              59.764359       3.750065
std    1125.977353    15.207589              23.685392       0.716983
min       1.000000    18.000000              20.000000       2.500000
25%     975.750000    31.000000              39.000000       3.100000
50%    1950.500000    44.000000              60.000000       3.800000
75%    2925.250000    57.000000              81.000000       4.400000
max    3900.000000    70.000000             100.000000       5.000000

       Previous Purchases
count         3900.000000
mean            25.351538
std             14.447125
min              1.000000
25%             13.000000
50%             25.000000
75%             38.000000
max             50.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB
None

In [4]:
print("\nShape of the data set:", df.shape) # Number of rows and columns in the data set
print("\nData types of each column:") 
print(df.columns) #List of columns in the data set
print("\nNumber of unique customer IDs:", df['Customer ID'].nunique()) # Number of unique customer ids in the data set

Shape of the data set: (3900, 18)

Data types of each column:
Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

Number of unique customer IDs: 3900

In [5]:
# Operation on the data set
print("=" * 70)

# Print the number of unique customer IDs in the data set
print("\nNumber of unique customer IDs:", df['Customer ID'].nunique()) # Number of unique customer ids in the data set

# Find out unique keys in frequency column
print("\nUnique keys in frequency column:")
print(df['Frequency of Purchases'].unique()) # Unique keys in frequency column

# Find out unique keys in Category column 
print("\nUnique keys in Category column:")
print(df['Category'].unique()) # Unique keys in Category column

# Find out unique keys in Item Purchased column
print("\nUnique keys in Item Purchased column:")
print(df['Item Purchased'].unique()) # Unique keys in Item Purchased column

# Find out unique for Season column
print("\nUnique keys in Season column:")
print(df['Season'].unique()) # Unique keys in Season column

#Find out unique for Shipping Mode column
print("\nUnique keys in Shipping Mode column:")
print(df['Shipping Type'].unique()) # Unique keys in Shipping Mode column

# Find out unique for Payment Method column
print("\nUnique keys in Payment Method column:")
print(df['Payment Method'].unique()) # Unique keys in Payment Method column

# Find out unique for location column
print("\nUnique keys in Location column:")
print(df['Location'].unique()) # Unique keys in Location column

======================================================================

Number of unique customer IDs: 3900

Unique keys in frequency column:
['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

Unique keys in Category column:
['Clothing' 'Footwear' 'Outerwear' 'Accessories']

Unique keys in Item Purchased column:
['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']

Unique keys in Season column:
['Winter' 'Spring' 'Summer' 'Fall']

Unique keys in Shipping Mode column:
['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']

Unique keys in Payment Method column:
['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']

Unique keys in Location column:
['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']

In [6]:
# List of null values in the data set
print("\nSum of Null values in each column:")
print(df.isnull().sum()) # List of null values in the data set

Sum of Null values in each column:
Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

<div style="font-family: 'AnthropicSerif', serif; font-size: 20px;">
Identified 37 missing values in  'Review Rating'.

Rather than potentially biasing the data with mean imputation for subjective reviews, I treated these as 'Unengaged' customers and analyzed their purchase frequency separately to see if 'No Review' acts as an early churn signal.
</div>

In [7]:
# Implementation Logic
df['Review Rating'] = df['Review Rating'].fillna('Unengaged')
cus_with_no_review = df[df['Review Rating'] == 'Unengaged']
print("\nNumber of customers with no review:") # Number of customers
print(cus_with_no_review.shape[0])

Number of customers with no review:
37

### 📅 Frequency Hierarchy (High to Low)

| Order | Frequency | Days (Approx) | Segment Type |
| :--- | :--- | :--- | :--- |
| 1 | **Weekly** | 7 | Active User |
| 2 | **Bi-Weekly / Fortnightly** | 14 | Consistent User |
| 3 | **Monthly** | 30 | Regular User |
| 4 | **Quarterly / Every 3 Months** | 90 | Seasonal User |
| 5 | **Annually** | 365 | Occasional User |

In [8]:
# Applying the feature engineering to the data set

#Convert the object Male/Female into 1/0
df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})

# Convert the object Subscription Status Yes/No into 1/0
df['Subscription Status'] = df['Subscription Status'].map({'Yes':1, 'No':0})

# Convert Discount Applied Yes/No into 1/0
df['Discount Applied'] = df['Discount Applied'].map({'Yes':1, 'No':0})

#Convert the Promo Code Used Yes/No into 1/0
df['Promo Code Used'] = df['Promo Code Used'].map({'Yes':1, 'No':0})

#Converting the Frequency of Purchases into numerical values 
# Mapping categorical frequency to ordinal integers
frequency_map = {
    'Weekly': 1, 
    'Bi-Weekly': 2, 
    'Fortnightly': 2, 
    'Monthly': 3, 
    'Every 3 Months': 4, 
    'Quarterly': 4, 
    'Annually': 5
}

df['Frequency of Purchases'] = df['Frequency of Purchases'].map(frequency_map)
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,1,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,1,Express,1,1,14,Venmo,2
1,2,19,1,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,1,Express,1,1,2,Cash,2
2,3,50,1,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,1,Free Shipping,1,1,23,Credit Card,1
3,4,21,1,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,1,Next Day Air,1,1,49,PayPal,1
4,5,45,1,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,1,Free Shipping,1,1,31,PayPal,5

### 📊 Strategic Breakdown

| Score | Logic | Segment Name | Business Meaning |
| :--- | :--- | :--- | :--- |
| **2 + Low Spend** | Both used AND spend < Median | **High Risk** | Only shops when margins are razor-thin. High churn risk. |
| **2** | Both used | **Heavy Discounter** | Strong preference for stackable deals. |
| **1** | Either used | **Casual Saver** | Normal consumer behavior; uses available deals. |
| **0** | None used | **Full Price** | Highly loyal or convenience-driven; best margins. |

In [9]:
# Discount dependency 

# Column which flags if a customer used BOTH a discount and a promo code
# 2 = Used Both, 1 = Used One, 0 = Used Neither
df['Discount_Dependency'] = (df['Discount Applied'] == 1).astype(int) + (df['Promo Code Used'] == 1).astype(int)

#High Rist Discount Flag
# Flagging users with low spend + discount usage
condition = [
    (df['Discount_Dependency'] == 2) & (df['Purchase Amount (USD)'] < df['Purchase Amount (USD)'].median()),    (df['Discount_Dependency'] == 2),
    (df['Discount_Dependency'] == 1),
    (df['Discount_Dependency'] == 0)
]

choices = [
    'High Risk (Bargain Hunter)', 
    'Heavy Discounter', 
    'Casual Saver', 
    'Full Price Shopper'
]

df['Discount_Risk_Profile'] = np.select(condition, choices, default='Other')

In [10]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Discount_Dependency,Discount_Risk_Profile
0,1,55,1,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,1,Express,1,1,14,Venmo,2,2,High Risk (Bargain Hunter)
1,2,19,1,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,1,Express,1,1,2,Cash,2,2,Heavy Discounter
2,3,50,1,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,1,Free Shipping,1,1,23,Credit Card,1,2,Heavy Discounter
3,4,21,1,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,1,Next Day Air,1,1,49,PayPal,1,2,Heavy Discounter
4,5,45,1,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,1,Free Shipping,1,1,31,PayPal,5,2,High Risk (Bargain Hunter)

In [11]:
# Estimate the Customer Lifetime Value (CLV)  (eCLV)
# Formula : eCLV = (Average Purchase Value) x (1 + Frequency of Previous Purchases)
df['eCLV'] = df['Purchase Amount (USD)'] * (1 + df['Frequency of Purchases'])
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Discount_Dependency,Discount_Risk_Profile,eCLV
0,1,55,1,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,1,Express,1,1,14,Venmo,2,2,High Risk (Bargain Hunter),159
1,2,19,1,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,1,Express,1,1,2,Cash,2,2,Heavy Discounter,192
2,3,50,1,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,1,Free Shipping,1,1,23,Credit Card,1,2,Heavy Discounter,146
3,4,21,1,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,1,Next Day Air,1,1,49,PayPal,1,2,Heavy Discounter,180
4,5,45,1,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,1,Free Shipping,1,1,31,PayPal,5,2,High Risk (Bargain Hunter),294

In [14]:
# Engagement Score the loyalty of the customer 
# Create a composite engagement score based on Subscription Status, Previous Purchase Frequency, and Review Rating, Frequency of Purchases and Discount Dependency

# Assigning weights to each component
# +3 Point for Subscription Status is 1 
# +3 Point for Previous Purchases greater than 15
# +2 Point for Review Rating greater than or equal to 4
# -3 Point for Discount Dependency of 2 (High Risk)
# -2 Point for Discount Dependency of 1 (Heavy Discounter)
# +2 Point for Frequency of Purchases between 1 and 2

def calculate_engagement_score(row):
    score = 0
    
    # 1. Subscription Loyalty (+2)
    if row['Subscription Status'] == 1:
        score += 3
        
    # 2. Purchase History (+2)
    if row['Previous Purchases'] > 15:
        score += 3

    # 3. High-Velocity Frequency (+1)
    # Target: Weekly (1) and Bi-Weekly (2) shoppers
    if 1 <= row['Frequency of Purchases'] <= 2:
        score += 2
        
    # 4. Customer Satisfaction (+2)
    # Using float conversion to ensure 'Unengaged' strings don't break the logic
    try:
        rating = float(row['Review Rating'])
        if rating >= 4:
            score += 2
    except (ValueError, TypeError):
        pass # Score remains 0 for non-numeric/missing ratings
        
    # 5. Discount Sensitivity (Penalties)
    if row['Discount_Dependency'] == 2:
        score -= 3
    elif row['Discount_Dependency'] == 1:
        score -= 2
        
    return score

# Applying the function to the dataframe
df['Engagement_Score'] = df.apply(calculate_engagement_score, axis=1)

### 📊 Engagement Score Logic

| Feature | Weight | Logic |
| :--- | :---: | :--- |
| **Subscription** | `+3` | Reward for recurring commitment. |
| **History** | `+3` | Reward for >15 previous purchases. |
| **Frequency** | `+2` | Reward for Weekly/Bi-Weekly shoppers. |
| **Satisfaction** | `+2` | Reward for Ratings ≥ 4. |
| **Discount Dep. (1)** | `-2` | Penalty for Casual Discount usage. |
| **Discount Dep. (2)** | `-3` | Penalty for "Bargain Hunter" behavior. |

**Final Scale:** $-3$ (Minimum) to $+10$ (Maximum)

In [17]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Discount_Dependency,Discount_Risk_Profile,eCLV,Engagement_Score
0,1,55,1,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Express,1,1,14,Venmo,2,2,High Risk (Bargain Hunter),159,2
1,2,19,1,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Express,1,1,2,Cash,2,2,Heavy Discounter,192,2
2,3,50,1,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Free Shipping,1,1,23,Credit Card,1,2,Heavy Discounter,146,5
3,4,21,1,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Next Day Air,1,1,49,PayPal,1,2,Heavy Discounter,180,5
4,5,45,1,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Free Shipping,1,1,31,PayPal,5,2,High Risk (Bargain Hunter),294,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,0,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,...,2-Day Shipping,0,0,32,Venmo,1,0,Full Price Shopper,56,7
3896,3897,52,0,Backpack,Accessories,49,Iowa,L,White,Spring,...,Store Pickup,0,0,41,Bank Transfer,2,0,Full Price Shopper,147,7
3897,3898,46,0,Belt,Accessories,33,New Jersey,L,Green,Spring,...,Standard,0,0,24,Venmo,4,0,Full Price Shopper,165,3
3898,3899,44,0,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,Express,0,0,24,Venmo,1,0,Full Price Shopper,154,5
3899,3900,52,0,Handbag,Accessories,81,California,M,Beige,Spring,...,Store Pickup,0,0,33,Venmo,4,0,Full Price Shopper,405,3

In [18]:
df.to_csv("/Users/rajuram/Desktop/working_with_ai/Decoding_Customer_Value/Gold_Customer_Data.csv", index=False)

In [19]:
import scipy.stats as stats

# Example A: t-test (2 groups)
group_a = df[df["Discount_Risk_Profile"] == "Full Price Shopper"]["Purchase Amount (USD)"]
group_b = df[df["Discount_Risk_Profile"] == "Heavy Discounter"]["Purchase Amount (USD)"]

t_stat, p_val = stats.ttest_ind(group_a, group_b, equal_var=False)
print("t-test p-value:", p_val)

# Example B: ANOVA (3+ groups)
groups = [
    df[df["Discount_Risk_Profile"] == label]["Purchase Amount (USD)"]
    for label in df["Discount_Risk_Profile"].unique()
]

f_stat, p_val = stats.f_oneway(*groups)
print("ANOVA p-value:", p_val)

# Example C: Chi-square (categorical vs categorical)
contingency = pd.crosstab(df["Subscription Status"], df["Discount_Risk_Profile"])
chi2, p_val, dof, expected = stats.chi2_contingency(contingency)
print("Chi-square p-value:", p_val)

t-test p-value: 2.8498601454313383e-175
ANOVA p-value: 0.0
Chi-square p-value: 0.0